# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-07 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpName', models.CharField(max_length=30)),
                ('createdOn', models.DateField(auto_now=True)),
                ('activeFlag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(max_length=200)),
                ('correctOption', models.CharField(max_length=2)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('image1', models.ImageField(default=None, upload_to='pic_folder/')),
                ('image2', models.ImageField(default=None, upload_to='pic_folder/')),
                ('maxMarks', models.IntegerField()),
                ('subject', models.CharField(default='NA', max_length=20)),
                ('subCategory', models.CharField(max_length=20)),
                ('difficultyLevel', models.IntegerField(default=2)),
                ('timeLimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=1)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('questionpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Question_Papers')),
            ],
        ),
        migrations.AddField(
            model_name='responses',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Session'),
        ),
        migrations.AddField(
            model_name='question_papers',
            name='questions',
            field=models.ManyToManyField(related_name='question', to='Question_Bank.Questions'),
        ),
        migrations.AddField(
            model_name='log',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Questions'),
        ),
        migrations.AddField(
            model_name='log',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Session'),
        ),
    ]
