# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreationDate', models.DateField(auto_now=True)),
                ('BeginFrom', models.DateField(auto_now=True)),
                ('Deadline', models.DateField(auto_now=True)),
                ('Topic', models.CharField(max_length=40)),
                ('Description', models.TextField(max_length=500)),
                ('SessionYear', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('ClassSection', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Students', models.IntegerField(default=0)),
                ('Subjects', models.IntegerField(default=0)),
                ('ClassPicture', models.ImageField(blank=True, upload_to='class_picture')),
                ('SessionYear', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAllotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionYear', models.CharField(max_length=9)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classes')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Login_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Personal_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('TeacherID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('ClassesPerWeek', models.IntegerField(default=0)),
                ('Qualification1', models.TextField(default='NA', max_length=50)),
                ('Qualification2', models.TextField(default='NA', max_length=50)),
                ('PreviousExperience', models.TextField(max_length=250)),
                ('ExperienceOfMonths', models.IntegerField(default=0)),
                ('Salary', models.IntegerField(default=0)),
                ('SessionYear', models.CharField(max_length=9)),
                ('Attribute1', models.CharField(max_length=20)),
                ('Attribute2', models.CharField(max_length=20)),
                ('Attribute3', models.CharField(max_length=20)),
                ('Attribute4', models.CharField(max_length=20)),
                ('Attribute5', models.CharField(max_length=20)),
                ('Attribute1Rating', models.IntegerField(default=0)),
                ('Attribute2Rating', models.IntegerField(default=0)),
                ('Attribute3Rating', models.IntegerField(default=0)),
                ('Attribute4Rating', models.IntegerField(default=0)),
                ('Attribute5Rating', models.IntegerField(default=0)),
                ('Subject1', models.CharField(default='', max_length=25)),
                ('Subject2', models.CharField(default='', max_length=25)),
                ('Subject3', models.CharField(default='', max_length=25)),
                ('Skill1', models.CharField(default=0, max_length=25)),
                ('Skill2', models.CharField(default=0, max_length=25)),
                ('Skill3', models.CharField(default=0, max_length=25)),
                ('Index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Personal_Info')),
            ],
        ),
        migrations.AddField(
            model_name='subjectallotment',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teachers'),
        ),
        migrations.AddField(
            model_name='classes',
            name='ClassTeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teachers'),
        ),
        migrations.AddField(
            model_name='classes',
            name='RoomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Rooms'),
        ),
        migrations.AddField(
            model_name='assigments',
            name='ClassSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classes'),
        ),
        migrations.AddField(
            model_name='assigments',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Subjects'),
        ),
        migrations.AddField(
            model_name='assigments',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teachers'),
        ),
    ]
