# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0007_auto_20171111_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes_2018',
            fields=[
                ('ClassSection', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Students', models.IntegerField(default=0)),
                ('Subjects', models.IntegerField(default=0)),
                ('From', models.DateField()),
                ('Till', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Q_Papers',
            fields=[
                ('QPaperID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Topic', models.TextField(max_length=25)),
                ('MaxMarks', models.IntegerField(default=0)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Appeared', models.IntegerField(default=0)),
                ('AvgMarks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_2018',
            fields=[
                ('TeacherID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('ClassesPerWeek', models.IntegerField(default=0)),
                ('Qualification', models.TextField(default='NA', max_length=50)),
                ('Experience', models.IntegerField(default=0)),
                ('Salary', models.IntegerField(default=0)),
                ('Index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Personal_Info')),
            ],
        ),
        migrations.AddField(
            model_name='q_papers',
            name='MadeBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teachers_2018'),
        ),
        migrations.AddField(
            model_name='q_papers',
            name='SubjectCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Subjects'),
        ),
        migrations.AddField(
            model_name='classes_2018',
            name='ClassTeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teachers_2018'),
        ),
        migrations.AddField(
            model_name='classes_2018',
            name='RoomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Rooms_2018'),
        ),
    ]
