# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_login_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes_2018',
            name='From',
        ),
        migrations.RemoveField(
            model_name='classes_2018',
            name='Till',
        ),
    ]
