# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_classes_classpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedOn', models.DateTimeField(auto_now=True)),
                ('DeadLine', models.DateTimeField(blank=True, null=True)),
                ('Task_Detail', models.CharField(max_length=100)),
                ('Priority', models.IntegerField(default=2)),
                ('Completed', models.BooleanField(default=False)),
            ],
        ),
    ]
