# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20171114_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q_papers',
            name='MadeBy',
        ),
        migrations.RemoveField(
            model_name='q_papers',
            name='SubjectCode',
        ),
        migrations.DeleteModel(
            name='Q_Papers',
        ),
    ]
