# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20171115_1338'),
        ('teacher', '0005_subjectallotment_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigments_2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Description', models.TextField(max_length=250)),
                ('ClassSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classes_2018')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Subjects')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teachers_2018')),
            ],
        ),
    ]
