# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.IntegerField(default=3)),
                ('Assigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Assigments')),
                ('GradingParameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.AssignmentParameters')),
            ],
        ),
        migrations.CreateModel(
            name='Student_login_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Personal_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('RegistrationNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('RollNo', models.CharField(default='NA', max_length=3)),
                ('NoOfSubjects', models.IntegerField(default=0)),
                ('AcademicScore', models.IntegerField(default=0)),
                ('ClassRank', models.IntegerField(default=0)),
                ('Attribute1', models.CharField(max_length=20)),
                ('Attribute2', models.CharField(max_length=20)),
                ('Attribute3', models.CharField(max_length=20)),
                ('Attribute4', models.CharField(max_length=20)),
                ('Attribute5', models.CharField(max_length=20)),
                ('Attribute1Rating', models.IntegerField(default=0)),
                ('Attribute2Rating', models.IntegerField(default=0)),
                ('Attribute3Rating', models.IntegerField(default=0)),
                ('Attribute4Rating', models.IntegerField(default=0)),
                ('Attribute5Rating', models.IntegerField(default=0)),
                ('Sibling1DOB', models.DateField(default='')),
                ('Sibling2DOB', models.DateField(default='')),
                ('ClassSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classes')),
                ('Index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Personal_Info')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionYear', models.CharField(max_length=9)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classes')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableLookUp',
            fields=[
                ('TTID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('WeekDay', models.CharField(max_length=9)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='TTID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.TimeTableLookUp'),
        ),
        migrations.AddField(
            model_name='assignmentgrades',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Students'),
        ),
    ]
