# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students_2018',
            fields=[
                ('RegistrationNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('RollNo', models.CharField(default='NA', max_length=3)),
                ('From', models.DateField()),
                ('Till', models.DateField()),
                ('NoOfSubjects', models.IntegerField(default=0)),
                ('AcademicScore', models.IntegerField(default=0)),
                ('ClassRank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableLookUp',
            fields=[
                ('TTID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('WeekDay', models.CharField(max_length=9)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_2018',
            fields=[
                ('RegistrationNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.Students_2018')),
                ('TTID', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='student.TimeTableLookUp')),
                ('ClassDate', models.DateField(primary_key=True)),
                ('Attendance', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable_2018',
            fields=[
                ('TTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.TimeTableLookUp')),
                ('ClassSection', models.CharField(max_length=3, primary_key=True)),
            ],
        ),
    ]
