# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable_2018',
            name='ClassSection',
        ),
        migrations.RemoveField(
            model_name='timetable_2018',
            name='SubjectCode',
        ),
        migrations.RemoveField(
            model_name='timetable_2018',
            name='TTID',
        ),
        migrations.DeleteModel(
            name='TimeTable_2018',
        ),
    ]
