# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        ('principal', '0007_auto_20171111_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_2018',
            name='ClassSection',
            field=models.ForeignKey(default='NA', max_length=3, on_delete=django.db.models.deletion.CASCADE, to='teacher.Classes_2018'),
        ),
        migrations.AddField(
            model_name='students_2018',
            name='Index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Personal_Info'),
        ),
        migrations.AddField(
            model_name='timetable_2018',
            name='SubjectCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Subjects'),
        ),
        migrations.AddField(
            model_name='timetable_2018',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teachers_2018'),
        ),
    ]
