# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-07 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Sibling1DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Sibling2DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
