# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_2018',
            name='ClassDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance_2018',
            name='RegistrationNo',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='student.Students_2018'),
        ),
        migrations.AlterField(
            model_name='attendance_2018',
            name='TTID',
            field=models.ForeignKey(default='NA', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='student.TimeTableLookUp'),
        ),
        migrations.AlterField(
            model_name='timetable_2018',
            name='ClassSection',
            field=models.CharField(default='NA', max_length=3),
        ),
    ]
