# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20171115_0749'),
        ('teacher', '0004_auto_20171115_0749'),
        ('student', '0002_auto_20171115_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable_2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classes_2018')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Subjects')),
                ('TTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.TimeTableLookUp')),
            ],
        ),
    ]
