# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20171112_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable_2018',
            name='ClassSection',
        ),
        migrations.AddField(
            model_name='timetablelookup',
            name='ClassSection',
            field=models.CharField(default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='attendance_2018',
            name='TTID',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='student.TimeTableLookUp', unique=True),
        ),
    ]
