# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20171112_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance2018LookUp',
            fields=[
                ('AttendanceID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ClassDate', models.DateField()),
                ('RegistrationNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Students_2018')),
                ('TTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.TimeTableLookUp')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance_2018',
            name='ClassDate',
        ),
        migrations.RemoveField(
            model_name='attendance_2018',
            name='RegistrationNo',
        ),
        migrations.RemoveField(
            model_name='attendance_2018',
            name='TTID',
        ),
        migrations.AddField(
            model_name='attendance_2018',
            name='AttendanceID2018',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.Attendance2018LookUp'),
        ),
    ]
