# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20171112_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_2018',
            name='AttendanceID2018',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.Attendance2018LookUp', unique=True),
        ),
    ]
