# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20171115_1338'),
        ('teacher', '0006_assigments_2018'),
        ('student', '0004_assignmentgrades_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentgrades_2018',
            name='Assigment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Assigments_2018'),
        ),
        migrations.AddField(
            model_name='assignmentgrades_2018',
            name='GradingParameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.AssignmentParameters'),
        ),
        migrations.AddField(
            model_name='assignmentgrades_2018',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Students_2018'),
        ),
    ]
