# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20171115_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_2018',
            name='ClassSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classes_2018'),
        ),
    ]
