# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GradingParameter', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='login_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('Index', models.IntegerField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('MiddleName', models.CharField(blank=True, max_length=20, null=True)),
                ('LastName', models.CharField(max_length=20)),
                ('ProfilePicture', models.ImageField(blank=True, upload_to='profile_image')),
                ('DOB', models.DateField()),
                ('Sex', models.CharField(max_length=12)),
                ('Contact', models.CharField(max_length=12)),
                ('SecondaryContact', models.CharField(default='', max_length=12)),
                ('EMail', models.CharField(max_length=40)),
                ('SecondaryEMail', models.CharField(default='', max_length=40)),
                ('BloodGroup', models.CharField(max_length=3)),
                ('AddressLine1', models.TextField(max_length=60)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=6)),
                ('CommuteDistance', models.FloatField()),
                ('CommuteTime', models.IntegerField()),
                ('CommuteBy', models.CharField(max_length=10)),
                ('JoiningDate', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('RoomID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Capacity', models.IntegerField(default=0)),
                ('RoomImage', models.ImageField(blank=True, upload_to='room_image')),
                ('Floor', models.IntegerField(default=0)),
                ('Fans', models.IntegerField(default=0)),
                ('Lights', models.IntegerField(default=0)),
                ('AC', models.IntegerField(default=0)),
                ('Windows', models.IntegerField(default=0)),
                ('Doors', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='School_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=60)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Pincode', models.CharField(max_length=6)),
                ('Contact1', models.CharField(max_length=12)),
                ('Contact2', models.CharField(max_length=12)),
                ('Contact3', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('SubjectCode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=20)),
                ('Description', models.TextField(max_length=200)),
                ('SubjectImage', models.ImageField(blank=True, upload_to='subject_image')),
                ('Books', models.TextField(max_length=150)),
                ('Prerequisites', models.TextField(max_length=150)),
                ('NoOfTeachers', models.IntegerField(default=0)),
                ('BaseSubject', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=10)),
                ('DifficultyLevel', models.IntegerField(default=2)),
                ('AvgScore', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='login_info',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Personal_Info'),
        ),
    ]
