# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='ProfilePicture',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='RoomImage',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='SubjectImage',
        ),
    ]
