# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]
