# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20180407_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Text', models.TextField(max_length=600)),
                ('Status', models.CharField(default='Unread', max_length=10)),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='principal.Personal_Info')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='principal.Personal_Info')),
            ],
        ),
    ]
