# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20171111_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal_Info',
        ),
    ]
