# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0003_delete_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('Index', models.IntegerField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('MiddleName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Sex', models.CharField(max_length=12)),
                ('Contact', models.CharField(max_length=12)),
                ('EMail', models.CharField(max_length=25)),
                ('BloodGroup', models.CharField(max_length=3)),
                ('AddressLine1', models.TextField(max_length=50)),
                ('AddressLine2', models.CharField(max_length=50)),
                ('AddressLine3', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=6)),
                ('CommuteDistance', models.IntegerField()),
                ('CommuteTime', models.IntegerField()),
                ('CommuteBy', models.CharField(max_length=10)),
            ],
        ),
    ]
