# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedbackID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('GivenBy', models.CharField(max_length=20)),
                ('GivenFor', models.CharField(max_length=20)),
                ('SubjectDifficulty', models.IntegerField(default=0, max_length=1)),
                ('CreateInterest', models.IntegerField(default=0, max_length=1)),
                ('HomeWorkLoad', models.IntegerField(default=0, max_length=1)),
                ('OverallPerformance', models.IntegerField(default=0, max_length=1)),
                ('Suggestions', models.TextField(default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms_2018',
            fields=[
                ('RoomID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Capacity', models.IntegerField(max_length=3)),
                ('Floor', models.IntegerField(max_length=2)),
                ('Fans', models.IntegerField(max_length=2)),
                ('Lights', models.IntegerField(max_length=2)),
                ('AC', models.IntegerField(max_length=2)),
                ('Windows', models.IntegerField(max_length=2)),
                ('Doors', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('SubjectCode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=20)),
                ('TaughtSince', models.DateField(auto_now=True)),
                ('TaughtTill', models.DateField(auto_now=True)),
                ('NoOfTeachers', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='SubjectCode',
            field=models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='principal.Subjects'),
        ),
    ]
