# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20171111_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='CreateInterest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='HomeWorkLoad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='OverallPerformance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='SubjectDifficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='NoOfTeachers',
            field=models.IntegerField(default=0),
        ),
    ]
