# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20171111_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms_2018',
            name='AC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms_2018',
            name='Capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms_2018',
            name='Doors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms_2018',
            name='Fans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms_2018',
            name='Floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms_2018',
            name='Lights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms_2018',
            name='Windows',
            field=models.IntegerField(default=0),
        ),
    ]
