# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20171111_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
