# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20171111_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='TaughtSince',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='TaughtTill',
        ),
    ]
