# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20171114_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='SubjectCode',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
