# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20171115_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GradingParamenter', models.CharField(max_length=20)),
            ],
        ),
    ]
