# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_assignmentparameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentparameters',
            old_name='GradingParamenter',
            new_name='GradingParameter',
        ),
    ]
