# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_auto_20180303_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 3, 3, 18, 49, 54, 608946, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
