# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-04 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_question_question_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.FileField(upload_to='media/')),
                ('of_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.QuestionPaper')),
                ('of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Students')),
            ],
        ),
    ]
