# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_answersheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('of_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Question')),
                ('of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Students')),
            ],
        ),
    ]
