# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0008_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('of_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Question')),
            ],
        ),
    ]
