# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('checker', '0009_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('of_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Parameters')),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='in_class',
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='of_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Students'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='of_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Students'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='of_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classes'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.AddField(
            model_name='parametermarks',
            name='of_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Students'),
        ),
    ]
